#!/bin/bash

GIT_GZIP=.git.tgz
GIT_DIR="${GIT_DIR:-.git}"

function say()
{
    echo "zgit:" "$@" >&2
}

function dbg()
{
    if [ -n "$ZGIT_VERBOSE" ]
    then
        say "$@"
    fi
}

if [ -d "$GIT_DIR" ]
then
    say "this appears to be a regular Git repo, to migrate to zgit run:"
    say "    tar caf $GIT_GZIP $GIT_DIR && rm -rf $GIT_DIR"
    exit 9
fi

ZGIT_DIR=$(mktemp -d zgit-XXXXXXXX)

if [ -e "$GIT_GZIP" ]
then
    dbg "uncompressing $GIT_GZIP to $ZGIT_DIR"

    tar -xf "$GIT_GZIP" -C "$ZGIT_DIR"

    if [ ! -d "$ZGIT_DIR/.git" ]
    then
        say ".git directory not found after decompression of $GIT_GZIP"
        rm -rf "$ZGIT_DIR"
        exit 9
    fi

    if [ "$?" -ne 0 ]
    then
        say "$GIT_GZIP uncompression failed."
        rm -rf "$ZGIT_DIR"
        exit 9
    fi
else
    ZGIT_DIR=$(mktemp -d)
fi

GIT_DIR="$ZGIT_DIR/.git" git "$@"
ret=$?

if [ -d "$ZGIT_DIR/.git" ]
then
    dbg "compressing $ZGIT_DIR..."
    tar -caf "$GIT_GZIP" -C "$ZGIT_DIR" .git
fi

rm -rf "$ZGIT_DIR"

exit $ret
